In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")

In [3]:
df=pd.read_csv("data\creditcard.csv")
df.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0

In [4]:
time_h=pd.to_timedelta(df['Time'],unit="s")

In [5]:
df['Hours']=(time_h.dt.components.hours).astype(int)

In [18]:
df.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V22,V23,V24,V25,V26,V27,V28,Amount,Class,Hours
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0,0

In [8]:
df['Hours'].value_counts()

Hours
21    17703
18    17039
11    16856
20    16756
10    16598
14    16570
15    16461
16    16453
17    16166
9     15838
19    15649
22    15441
12    15420
13    15365
23    10938
8     10276
0      7695
7      7243
1      4220
6      4101
3      3492
2      3328
5      2990
4      2209
Name: count, dtype: int64

In [3]:
legit = df[df['Class']==0]
fraud= df[df['Class']==1]

In [4]:
print("fraud:",fraud.shape)
print("legit:",legit.shape)

fraud: (492, 31)
legit: (284315, 31)

In [5]:
legit_sample_data=legit.sample(n=492)

In [6]:
sample_data_set=pd.concat([legit_sample_data,fraud],axis=0)

In [7]:
sample_data_set["Class"].value_counts()

Class
0    492
1    492
Name: count, dtype: int64

In [9]:
X=sample_data_set.drop("Class",axis=1)
Y=sample_data_set['Class']

In [12]:
X.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
82438,59400.0,1.194860,-1.023140,0.341673,-1.637797,-1.135230,-0.298228,-0.686216,-0.027491,0.346161,...,-0.326181,-0.352276,-0.592260,-0.019795,-0.469379,0.290620,-0.733051,0.100695,0.047664,95.85
166555,118157.0,-0.173895,0.834185,2.651017,4.514929,0.136188,0.973530,-0.203066,0.133586,-1.132918,...,0.320064,0.061944,0.386792,-0.017408,-0.142453,-0.870675,0.228859,0.070045,-0.023116,10.61
23789,32918.0,0.994361,-0.400000,1.068266,1.275173,-0.773585,0.785689,-0.810983,0.498484,0.865760,...,-0.170787,0.001049,0.006442,-0.043593,-0.348097,0.268561,-0.359485,0.062148,0.025634,56.00
37692,39065.0,-1.434123,0.126959,1.443860,-0.498100,0.685506,-0.558533,1.381490,-0.026542,-1.333894,...,0.445298,-0.088798,-0.789718,0.350410,0.208458,0.292194,0.045129,-0.103643,0.063628,169.95
25915,33821.0,-1.145227,0.073757,1.977504,1.235130,-1.922113,1.523276,1.514842,-0.018558,0.417990,...,0.078821,0.116099,0.761059,-0.079791,-0.053855,0.672927,0.034198,0.177896,-0.027005,393.46

In [14]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

In [15]:
x_train,x_test,y_train,y_test=train_test_split(X,Y,train_size=0.2,random_state=42)